package com.cinequiz

data class QuizQuestion(
    val category: String,
    val question: String,
    val options: List<String>,
    val correct: Int,
)

object QuizQuestions {

    val all: List<QuizQuestion> = listOf(
        QuizQuestion("Anime", "Which anime features a notebook that kills anyone whose name is written in it?", listOf("Death Note", "Code Geass", "Monster", "Steins;Gate"), 0),
        QuizQuestion("Anime", "In Naruto, what is the name of the nine-tailed beast sealed inside Naruto?", listOf("Shukaku", "Kurama", "Matatabi", "Gyuki"), 1),
        QuizQuestion("Anime", "Who is the creator of One Piece?", listOf("Masashi Kishimoto", "Tite Kubo", "Eiichiro Oda", "Yoshihiro Togashi"), 2),
        QuizQuestion("Anime", "In Dragon Ball Z, what is the highest Super Saiyan form Goku reaches in the original Z run?", listOf("Super Saiyan 2", "Super Saiyan 3", "Super Saiyan 4", "Super Saiyan God"), 1),
        QuizQuestion("Anime", "Which guild does Lucy Heartfilia join in Fairy Tail?", listOf("Blue Pegasus", "Sabertooth", "Fairy Tail", "Phantom Lord"), 2),
        QuizQuestion("Anime", "In Attack on Titan, what is the name of Eren's home district?", listOf("Trost", "Shiganshina", "Stohess", "Ragako"), 1),
        QuizQuestion("Anime", "What fruit did Luffy eat?", listOf("Flame-Flame Fruit", "Gum-Gum Fruit", "Dark-Dark Fruit", "Op-Op Fruit"), 1),
        QuizQuestion("Anime", "In My Hero Academia, what is All Might's real name?", listOf("Toshinori Yagi", "Enji Todoroki", "Shota Aizawa", "Hizashi Yamada"), 0),
        QuizQuestion("Anime", "In Fullmetal Alchemist, what did Edward lose in the failed transmutation?", listOf("His sight", "His leg", "His arm", "Both a leg and an arm"), 3),
        QuizQuestion("Anime", "Who is the strongest swordsman in the world in One Piece?", listOf("Roronoa Zoro", "Dracule Mihawk", "Shanks", "Kaido"), 1),
        QuizQuestion("Anime", "In Demon Slayer, which breathing style does Tanjiro initially learn?", listOf("Thunder Breathing", "Flame Breathing", "Water Breathing", "Wind Breathing"), 2),
        QuizQuestion("Anime", "What are the three walls called in Attack on Titan?", listOf("Maria, Rose and Sina", "Alpha, Beta and Gamma", "North, South and East", "Eden, Zion and Mara"), 0),
        QuizQuestion("Anime", "In Jujutsu Kaisen, what grade of curse is Sukuna?", listOf("Special Grade", "Grade 1", "Grade 4", "Semi-Grade 1"), 0),
        QuizQuestion("Anime", "Which studio animated Spirited Away?", listOf("Studio Ghibli", "Madhouse", "Kyoto Animation", "Bones"), 0),
        QuizQuestion("Anime", "In Bleach, what is the name of Ichigo's zanpakuto?", listOf("Senbonzakura", "Zangetsu", "Hyorinmaru", "Ryujin Jakka"), 1),
        QuizQuestion("Anime", "Hunter x Hunter protagonist Gon wants to find which person?", listOf("His mother", "His father Ging", "His brother", "Killua"), 1),
        QuizQuestion("Anime", "In Cowboy Bebop, what is the name of the spaceship the crew lives on?", listOf("Swordfish", "Bebop", "Red Tail", "Outlaw Star"), 1),
        QuizQuestion("Anime", "What sport does the anime Haikyuu center on?", listOf("Basketball", "Volleyball", "Tennis", "Baseball"), 1),
        QuizQuestion("Anime", "In One Punch Man, what is Saitama's main problem as a hero?", listOf("He is too weak", "He is too strong", "He has no license", "He is always injured"), 1),
        QuizQuestion("Anime", "In Vinland Saga, who killed Thorfinn's father?", listOf("Askeladd", "Thors", "Canute", "Floki"), 0),
        QuizQuestion("Anime", "In Spy x Family, what is Anya's secret power?", listOf("Reading minds", "Turning invisible", "Flying", "Stopping time"), 0),
        QuizQuestion("Anime", "In Chainsaw Man, what is Denji's devil dog named?", listOf("Pochita", "Meowy", "Beam", "Aki"), 0),
        QuizQuestion("Anime", "In Dr. Stone, what is Senku's main goal?", listOf("Conquer the world", "Rebuild civilization with science", "Only cure petrification", "Return to the past"), 1),
        QuizQuestion("Anime", "What is the name of the floating castle in Sword Art Online?", listOf("Aincrad", "Alfheim", "Underworld", "Astra"), 0),
        QuizQuestion("Anime", "In Neon Genesis Evangelion, what is NERV's half slogan that ends with 'all's right with the world'?", listOf("God's in his heaven", "Seele guides us", "Angels fear us", "Tokyo stands"), 0),
        QuizQuestion("Anime", "In Naruto, which team is Kakashi the leader of?", listOf("Team 7", "Team 8", "Team 10", "Team Guy"), 0),
        QuizQuestion("Anime", "What is Light Yagami's alias in Death Note?", listOf("L", "Kira", "Near", "Mello"), 1),
        QuizQuestion("Anime", "In One Piece, what is Zoro's dream?", listOf("To be Pirate King", "To be the world's strongest swordsman", "To map the world", "To be an admiral"), 1),
        QuizQuestion("Anime", "Which anime follows a doctor treating a boy who survived a massacre?", listOf("Black Jack", "Monster", "Vampire Knight", "Cells at Work"), 1),
        QuizQuestion("Anime", "In Frieren, what is Frieren's race?", listOf("Human", "Elf", "Dwarf", "Demon"), 1),
        QuizQuestion("Hollywood", "Which movie features the line 'May the Force be with you'?", listOf("Star Trek", "Star Wars", "Dune", "Battlestar Galactica"), 1),
        QuizQuestion("Hollywood", "Who directed Jurassic Park?", listOf("James Cameron", "Steven Spielberg", "Ridley Scott", "George Lucas"), 1),
        QuizQuestion("Hollywood", "In The Matrix, which pill does Neo take?", listOf("Blue", "Red", "Green", "White"), 1),
        QuizQuestion("Hollywood", "Who played Iron Man in the Marvel Cinematic Universe?", listOf("Chris Evans", "Mark Ruffalo", "Robert Downey Jr", "Chris Hemsworth"), 2),
        QuizQuestion("Hollywood", "In Inception, what does the spinning top signify for Cobb?", listOf("His totem for dream detection", "A trophy", "His childhood toy", "A gift from his wife"), 0),
        QuizQuestion("Hollywood", "Which movie won the first Academy Award for Best Animated Feature?", listOf("Toy Story", "Shrek", "Spirited Away", "Monsters, Inc"), 1),
        QuizQuestion("Hollywood", "In The Dark Knight, who played the Joker?", listOf("Jack Nicholson", "Heath Ledger", "Jared Leto", "Joaquin Phoenix"), 1),
        QuizQuestion("Hollywood", "In Lord of the Rings, what is the name of the hobbit played by Elijah Wood?", listOf("Samwise Gamgee", "Frodo Baggins", "Merry Brandybuck", "Pippin Took"), 1),
        QuizQuestion("Hollywood", "In Titanic, what are the names of the lead couple?", listOf("Jack and Rose", "Cal and Ruth", "Brock and Bodine", "Fabrizio and Helga"), 0),
        QuizQuestion("Hollywood", "Which film features Jack Torrance and the Overlook Hotel?", listOf("Psycho", "The Shining", "Hereditary", "It"), 1),
        QuizQuestion("Hollywood", "Who directed Pulp Fiction?", listOf("Martin Scorsese", "Quentin Tarantino", "The Coen Brothers", "David Fincher"), 1),
        QuizQuestion("Hollywood", "In Interstellar, what does Cooper leave for his daughter Murph?", listOf("A watch", "A book", "A photograph", "A model spaceship"), 0),
        QuizQuestion("Hollywood", "What is Deadpool's real name?", listOf("Wade Wilson", "Logan Howlett", "Scott Summers", "Frank Castle"), 0),
        QuizQuestion("Hollywood", "In The Godfather, what is Don Corleone's first name?", listOf("Santino", "Michael", "Vito", "Fredo"), 2),
        QuizQuestion("Hollywood", "Which movie is about a linguist communicating with heptapod aliens?", listOf("Contact", "Arrival", "Annihilation", "Close Encounters"), 1),
        QuizQuestion("Hollywood", "In Forrest Gump, what does Forrest say life is like?", listOf("A journey", "A box of chocolates", "A rollercoaster", "A dream"), 1),
        QuizQuestion("Hollywood", "Who composed the score for The Lion King 1994?", listOf("John Williams", "Hans Zimmer", "Danny Elfman", "Alan Menken"), 1),
        QuizQuestion("Hollywood", "In Gladiator, what was Maximus before becoming a slave?", listOf("Senator", "General", "Merchant", "Gladiator trainer"), 1),
        QuizQuestion("Hollywood", "In Back to the Future, what speed activates the DeLorean's time travel?", listOf("88 mph", "100 mph", "66 mph", "120 mph"), 0),
        QuizQuestion("Hollywood", "Who directed the 2019 Joker film?", listOf("Todd Phillips", "Denis Villeneuve", "David Ayer", "Zack Snyder"), 0),
        QuizQuestion("Hollywood", "In Mad Max: Fury Road, what is Furiosa searching for?", listOf("The Green Place", "Gas Town", "The Citadel", "Bullet Farm"), 0),
        QuizQuestion("Hollywood", "Which film won Best Picture at the 2020 Oscars?", listOf("1917", "Parasite", "Joker", "Once Upon a Time in Hollywood"), 1),
        QuizQuestion("Hollywood", "In Whiplash, what instrument does Andrew play?", listOf("Piano", "Drums", "Saxophone", "Trumpet"), 1),
        QuizQuestion("Hollywood", "In The Prestige, what are the three parts of a magic trick?", listOf("Setup, Turn, Prestige", "Act One, Two, Three", "Reveal, Twist, End", "Pledge, Turn, Prestige"), 3),
        QuizQuestion("Hollywood", "In Se7en, what is in the box?", listOf("A head", "A heart", "A gun", "A photograph"), 0),
        QuizQuestion("Hollywood", "Which actor made 'I'll be back' famous?", listOf("Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Kurt Russell"), 1),
        QuizQuestion("Hollywood", "Which animated movie is about emotions inside a girl's head?", listOf("Inside Out", "Soul", "Coco", "Onward"), 0),
        QuizQuestion("Bollywood", "Which Bollywood film features 'Chaiyya Chaiyya' danced on top of a train?", listOf("Dil Se", "Dilwale Dulhania Le Jayenge", "Kuch Kuch Hota Hai", "Rangeela"), 0),
        QuizQuestion("Bollywood", "Who is popularly called the King of Bollywood?", listOf("Salman Khan", "Aamir Khan", "Shah Rukh Khan", "Amitabh Bachchan"), 2),
        QuizQuestion("Bollywood", "In Sholay, what is the name of Amitabh Bachchan's character?", listOf("Veeru", "Jai", "Thakur", "Gabbar"), 1),
        QuizQuestion("Bollywood", "Which movie is about a wrestler who trains his daughters to fight?", listOf("Sultan", "Dangal", "Gold", "Chak De! India"), 1),
        QuizQuestion("Bollywood", "Who directed Lagaan?", listOf("Ashutosh Gowariker", "Rajkumar Hirani", "Karan Johar", "Sanjay Leela Bhansali"), 0),
        QuizQuestion("Bollywood", "In 3 Idiots, what is Rancho's real identity?", listOf("Chatur's classmate", "Farhan's brother", "Phunsukh Wangdu", "Raju's cousin"), 2),
        QuizQuestion("Bollywood", "Which film stars Aamir Khan as an alien questioning religion?", listOf("PK", "Talaash", "Dhoom 3", "Ghajini"), 0),
        QuizQuestion("Bollywood", "What does DDLJ stand for?", listOf("Dilwale Dulhania Le Jayenge", "Dil Diwana Deewana Junoon", "Dulhan Dulhania Le Jayenge", "Dil Deewana Le Jayenge"), 0),
        QuizQuestion("Bollywood", "Who played Milkha Singh in Bhaag Milkha Bhaag?", listOf("Akshay Kumar", "Farhan Akhtar", "Ranbir Kapoor", "Hrithik Roshan"), 1),
        QuizQuestion("Bollywood", "In Gangs of Wasseypur, which industry is central to the story?", listOf("Coal mining", "Textiles", "Sugar", "Timber"), 0),
        QuizQuestion("Bollywood", "In Queen, where does Rani go on her honeymoon alone?", listOf("London", "Paris", "Amsterdam", "New York"), 2),
        QuizQuestion("Bollywood", "Who sang 'Tum Hi Ho' from Aashiqui 2?", listOf("Atif Aslam", "Arijit Singh", "Sonu Nigam", "Rahat Fateh Ali Khan"), 1),
        QuizQuestion("Bollywood", "In Andaz Apna Apna, what are the names of the two leads?", listOf("Amar and Prem", "Rahul and Raj", "Vicky and Prem", "Amar and Raj"), 0),
        QuizQuestion("Bollywood", "In Chak De! India, what sport does the women's team play?", listOf("Cricket", "Hockey", "Football", "Kabaddi"), 1),
        QuizQuestion("Bollywood", "In Zindagi Na Milegi Dobara, which country do the friends travel through?", listOf("Italy", "France", "Spain", "Portugal"), 2),
        QuizQuestion("Bollywood", "In Mughal-e-Azam, who played Anarkali?", listOf("Madhubala", "Meena Kumari", "Nargis", "Waheeda Rehman"), 0),
        QuizQuestion("Bollywood", "Which movie has the dialogue 'Mogambo khush hua'?", listOf("Karma", "Mr. India", "Shahenshah", "Hero"), 1),
        QuizQuestion("Bollywood", "In Swades, why does Mohan return to India?", listOf("A film shoot", "To find his nanny", "Business", "A wedding"), 1),
        QuizQuestion("Bollywood", "Which Shakespeare play is Omkara an adaptation of?", listOf("Hamlet", "Othello", "Macbeth", "King Lear"), 1),
        QuizQuestion("Bollywood", "Who composed the music for Devdas 2002?", listOf("A.R. Rahman", "Ismail Darbar", "Anu Malik", "Nadeem-Shravan"), 1),
        QuizQuestion("General", "Which streaming platform produced Stranger Things?", listOf("Hulu", "Netflix", "Amazon Prime", "HBO Max"), 1),
        QuizQuestion("General", "What was the first feature-length computer-animated film?", listOf("A Bug's Life", "Toy Story", "Antz", "Shrek"), 1),
        QuizQuestion("General", "Which actor played James Bond most times in official Eon films?", listOf("Sean Connery", "Roger Moore", "Daniel Craig", "Pierce Brosnan"), 1),
        QuizQuestion("General", "How many seasons does Friends have?", listOf("8", "9", "10", "11"), 2),
        QuizQuestion("General", "What is the best-selling video game of all time?", listOf("Tetris", "Minecraft", "GTA V", "Wii Sports"), 1),
        QuizQuestion("General", "Which country produces the most feature films per year?", listOf("USA", "India", "Nigeria", "China"), 1),
        QuizQuestion("General", "In Breaking Bad, what does Walter White teach?", listOf("Math", "Chemistry", "Physics", "Biology"), 1),
        QuizQuestion("General", "What year did the first Iron Man movie release?", listOf("2006", "2007", "2008", "2009"), 2),
        QuizQuestion("General", "In The Office US, what is Dwight's farm called?", listOf("Beet Farm", "Schrute Farms", "Dwight's Farm", "Lazy Acres"), 1),
        QuizQuestion("General", "Which planet is Superman from?", listOf("Mars", "Krypton", "Daxam", "Oa"), 1),
        QuizQuestion("General", "How many Infinity Stones are there in the MCU?", listOf("Five", "Six", "Seven", "Four"), 1),
        QuizQuestion("General", "In Game of Thrones, what is the motto of House Stark?", listOf("Fire and Blood", "Winter is Coming", "Hear Me Roar", "We Do Not Sow"), 1),
        QuizQuestion("General", "What is the longest running American animated show?", listOf("The Simpsons", "South Park", "Family Guy", "SpongeBob"), 0),
        QuizQuestion("General", "Who wrote the novel Fight Club is based on?", listOf("Bret Easton Ellis", "Chuck Palahniuk", "Irvine Welsh", "Douglas Coupland"), 1),
        QuizQuestion("General", "What is the name of Jack Sparrow's ship?", listOf("Dutchman", "Black Pearl", "Interceptor", "Queen Anne's Revenge"), 1),
        QuizQuestion("General", "Which film franchise features a hitman named John Wick?", listOf("Mission Impossible", "John Wick", "Bourne", "Taken"), 1),
        QuizQuestion("General", "What animation studio made Despicable Me?", listOf("Pixar", "DreamWorks", "Illumination", "Sony Pictures Animation"), 2),
        QuizQuestion("General", "In The Big Bang Theory, what does Sheldon call his spot on the couch?", listOf("My place", "My spot", "The throne", "Command central"), 1),
        QuizQuestion("General", "Which movie franchise has a car called the Batmobile?", listOf("Superman", "Batman", "Spider-Man", "Iron Man"), 1),
    )

    fun pick(count: Int): List<QuizQuestion> = all.shuffled().take(count)
}
