package com.toonworld4all

import android.content.Context
import com.lagradost.api.Log
import com.lagradost.cloudstream3.*
import com.lagradost.cloudstream3.utils.ExtractorLink
import com.lagradost.cloudstream3.utils.ExtractorLinkType
import com.lagradost.cloudstream3.utils.newExtractorLink
import com.lagradost.cloudstream3.plugins.CloudstreamPlugin
import com.lagradost.cloudstream3.plugins.Plugin
import kotlinx.coroutines.CancellationException
import org.jsoup.Jsoup
import java.util.concurrent.ConcurrentHashMap

@CloudstreamPlugin
class ToonWorld4AllPlugin : Plugin() {
    override fun load(context: Context) {
        // the background WebView harness needs an app context to exist
        Tw4aWebView.init(context)
        registerMainAPI(ToonWorld4All())
    }
}

/**
 * CloudStream provider for https://toonworld4all.me/
 *
 * PIPELINE (verified live, 2026-09):
 *
 *  1. toonworld4all.me (WordPress "Herald" theme)
 *     - mainPage: latest + tag/category archives (/page/N/ pagination)
 *     - search: /?s={query}
 *     - posts carry episode accordions ("Episode 01" -> mks_button) whose
 *       links point to archive.toonworld4all.me/episode/{slug}; movies carry
 *       a "Get Download Links" button -> archive.toonworld4all.me/movie/{slug}
 *
 *  2. archive.toonworld4all.me (SSR React app)
 *     - every page embeds window.__PROPS__ JSON: metadata (TMDB title/
 *       overview/poster) + encodes[] (resolution, codec, size, readable) +
 *       files[] (host + /redirect/{hash} link)
 *     - NOTE: the redirect hashes ROTATE on every page fetch (the encrypted
 *       payload contains a per-request nonce), so caching is keyed on
 *       episode+host+encode instead of the hash itself
 *     - hosts seen in production: HubCloud, Filepress, GDFlix, MEGA
 *
 *  3. /redirect/{hash} (server-side AES decrypt)
 *     - creates a FRESH exe.io short link per request via the exe.io API
 *       (api token is public in their JS bundle) and 302s/renders it
 *     - the visible link.domain + link.hidden on the chooser page is RANDOM
 *       JUNK generated by Fh() - only "destination" is real
 *
 *  4. Shortener chain exe.io -> exeygo.com (Tw4aWebView + Tw4aShortener)
 *     - p1: 6s countdown -> Continue button (data-ref="continue")
 *     - p2: Cloudflare Turnstile -> submit (data-ref="captcha") auto-enables
 *       once solved. The Turnstile iframe REQUIRES third-party cookies -
 *       Tw4aWebView enables them (WebViewResolver did not, which is why
 *       v2 failed with ".../failure_retry/..." loops on device). Popunder
 *       ads are blocked (no window.open, ad-domain navigations vetoed) and
 *       only the exact stage buttons are ever clicked.
 *
 *  5. File hosts (real URL finally known):
 *     - HubCloud   hubcloud.ist/video|file/{id} -> FSL/10Gbps/Mega/pixeldrain
 *     - GDFlix     gdflix.dev/file/{id} (302 -> new4.gdflix.io) -> Direct/
 *                  Cloud/GDIndex/FastCloud/Instant
 *     - Filepress  new4.filepress.baby/file/{id} (Cloudflare) -> drive links
 *     - MEGA       AES-encrypted, not playable by Android players -> skipped
 *
 * Resolution strategy: files are resolved ONE WebView at a time (parallel
 * Turnstile challenges on one device sabotage each other), best-guess encode
 * first (720p x264, then 1080p/480p x264, then HEVC), HubCloud before
 * GDFlix before Filepress. Resolved destinations are cached so re-opening
 * the source list is instant and progressively unlocks more files.
 */
class ToonWorld4All : MainAPI() {

    override var mainUrl = "https://toonworld4all.me"
    override var name = "ToonWorld4All"
    override var lang = "en"
    override val hasMainPage = true
    override val hasDownloadSupport = true

    /** WebView shortener walks are slow - ask the app for more time. */
    override val loadLinksTimeoutMs: Long? = 5 * 60_000L

    override val supportedTypes = setOf(
        TvType.Cartoon, TvType.Anime, TvType.Movie, TvType.TvSeries, TvType.AnimeMovie
    )

    override val mainPage = mainPageOf(
        "" to "Latest Updates",
        "category/anime" to "Anime (Hindi Dub)",
        "tag/eng-sub-anime" to "Anime (Eng Sub)",
        "tag/animated-series" to "Cartoon Shows",
        "tag/animated-movies" to "Animated Movies",
        "tag/hollywood-movies" to "Hollywood Movies",
        "category/netflix" to "Netflix",
    )

    private val headers = mapOf(
        "User-Agent" to "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
        "Accept" to "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language" to "en-US,en;q=0.9",
    )

    // ------------------------------------------------------------------ //
    //  mainPage / search
    // ------------------------------------------------------------------ //

    override suspend fun getMainPage(
        page: Int,
        request: MainPageRequest
    ): HomePageResponse {
        val section = request.data.trimEnd('/')
        val url = when {
            page <= 1 -> if (section.isEmpty()) "$mainUrl/" else "$mainUrl/$section/"
            else -> if (section.isEmpty()) "$mainUrl/page/$page/" else "$mainUrl/$section/page/$page/"
        }
        val html = fetchHtml(url)
            ?: throw ErrorLoadingException("Could not reach toonworld4all.me. Check your connection and retry.")
        val results = parsePostList(Jsoup.parse(html))
        if (results.isEmpty()) {
            // an empty listing means either a Cloudflare block the WebView
            // could not solve or a changed theme - do not silently show
            // "no sources" when the page itself did not load properly
            if (Tw4aWebView.isChallengeHtml(html)) {
                throw ErrorLoadingException("Cloudflare is blocking toonworld4all.me on this network. Retry, or try with a VPN.")
            }
        }
        return newHomePageResponse(request.name, results, results.isNotEmpty())
    }

    override suspend fun search(query: String): List<SearchResponse> {
        val results = mutableListOf<SearchResponse>()
        for (page in 1..3) {
            val url = if (page == 1) "$mainUrl/?s=${java.net.URLEncoder.encode(query, "UTF-8")}"
            else "$mainUrl/page/$page/?s=${java.net.URLEncoder.encode(query, "UTF-8")}"
            val html = try {
                fetchHtml(url) ?: break
            } catch (e: Exception) {
                if (e is CancellationException) throw e
                break
            }
            val found = parsePostList(Jsoup.parse(html))
            if (found.isEmpty()) break
            results.addAll(found.filter { it.url !in results.map { r -> r.url } })
        }
        return results
    }

    /** Parse a WordPress listing page (search results / archive / home). */
    private fun parsePostList(doc: org.jsoup.nodes.Document): List<SearchResponse> {
        val out = mutableListOf<SearchResponse>()
        for (article in doc.select("article")) {
            val a = article.selectFirst("h2.entry-title a") ?: continue
            val url = a.attr("href").trim()
            if (!url.startsWith(mainUrl)) continue
            val title = a.text().trim()
            if (title.isEmpty() || url == "$mainUrl/") continue

            val img = article.selectFirst(".herald-post-thumbnail img")
                ?: article.selectFirst("img[src]")
            val poster = img?.let {
                it.attr("src").ifBlank { it.attr("data-src") }
            }?.takeIf { it.startsWith("http") }

            val type = guessType(url, title, article.attr("class"))
            out.add(
                when (type) {
                    TvType.Movie, TvType.AnimeMovie ->
                        newMovieSearchResponse(title, url, type) { this.posterUrl = poster }
                    else ->
                        newTvSeriesSearchResponse(title, url, type) { this.posterUrl = poster }
                }
            )
        }
        return out
    }

    private fun guessType(url: String, title: String, classes: String): TvType {
        val hay = (url + " " + title + " " + classes).lowercase()
        val isAnime = hay.contains("anime")
        return when {
            hay.contains("movie") || hay.contains("film") ->
                if (isAnime) TvType.AnimeMovie else TvType.Movie
            isAnime -> TvType.Anime
            else -> TvType.Cartoon
        }
    }

    // ------------------------------------------------------------------ //
    //  network helpers - Cloudflare-aware, retried
    // ------------------------------------------------------------------ //

    /**
     * Fetch a page from toonworld4all.me with:
     *  - automatic retries (the device logcat showed transient DNS/IPv6
     *    failures - UnknownHostException, IPv6 connect timeouts)
     *  - Cloudflare bypass via the healthy WebView (Tw4aWebView.getWithCf)
     * Returns the html, or null when everything failed.
     */
    private suspend fun fetchHtml(url: String, attempts: Int = 3): String? {
        var lastHtml: String? = null
        for (attempt in 0 until attempts) {
            val html = Tw4aWebView.getWithCf(url, headers, timeoutSec = 25L)
            if (html != null) {
                if (!Tw4aWebView.isChallengeHtml(html)) return html
                lastHtml = html
                Log.d(TAG, "challenge persisted on attempt ${attempt + 1} for $url")
            }
            if (attempt < attempts - 1) kotlinx.coroutines.delay(700L * (attempt + 1))
        }
        return lastHtml
    }

    override suspend fun load(url: String): LoadResponse? {
        val html = fetchHtml(url)
            ?: throw ErrorLoadingException("Could not reach toonworld4all.me. Check your connection and retry.")

        // Cloudflare block the WebView could not solve - say so instead of
        // the old misleading "no archive links" error
        if (Tw4aWebView.isChallengeHtml(html)) {
            throw ErrorLoadingException("Cloudflare is blocking toonworld4all.me on this network. Retry, or try with a VPN.")
        }

        val doc = Jsoup.parse(html)

        val title = doc.selectFirst("h1.entry-title")?.text()?.trim()
            ?: doc.selectFirst("meta[property=og:title]")?.attr("content")?.trim()
            ?: url.trimEnd('/').substringAfterLast('/')

        val poster = doc.selectFirst("meta[property=og:image]")?.attr("content")?.takeIf { it.startsWith("http") }
        val year = Regex("""\((\d{4})\)""").find(title)?.groupValues?.get(1)?.toIntOrNull()

        val bodyText = doc.selectFirst("div.entry-content")?.text().orEmpty()
        val synopsis = bodyText.substringAfter("Synopsis:", "").substringBefore("Screenshots")
            .trim().ifBlank {
                doc.selectFirst("meta[property=og:description]")?.attr("content")?.trim()
            }

        val tags = doc.select("div.meta-tags a").map { it.text().lowercase() }
        val isAnime = tags.any { it.contains("anime") } ||
                title.contains("anime", true) ||
                url.contains("anime")

        // ---- archive links (anywhere in the post) ---- //
        val movieLinks = doc.select("a[href]")
            .map { it.attr("href") }
            .filter { it.contains("archive.toonworld4all.me/movie/") }
            .distinct()

        val episodeLinks = doc.select("a[href]")
            .map { it.attr("href") }
            .filter { it.contains("archive.toonworld4all.me/episode/") }
            .distinct()

        // ---- movie ---- //
        if (movieLinks.isNotEmpty()) {
            val data = movieLinks.first()
            return newMovieLoadResponse(
                title, url,
                if (isAnime) TvType.AnimeMovie else TvType.Movie,
                data
            ) {
                this.posterUrl = poster
                this.year = year
                this.plot = synopsis
            }
        }

        // ---- series ---- //
        val episodes = parseEpisodes(doc, episodeLinks)
        if (episodes.isNotEmpty()) {
            return newTvSeriesLoadResponse(
                title, url,
                if (isAnime) TvType.Anime else TvType.Cartoon,
                episodes
            ) {
                this.posterUrl = poster
                this.year = year
                this.plot = synopsis
                this.showStatus = null
            }
        }

        // Old-format post (direct gplinks/batch links, no archive system) -
        // only report this when the page REALLY is a post without archive
        // links (challenge pages never get this far)
        if (doc.selectFirst("div.entry-content") != null) {
            throw ErrorLoadingException("This post has no archive links (old format). Open it in a browser.")
        }
        throw ErrorLoadingException("Could not load this post - the page did not parse. Retry.")
    }

    /**
     * Build the episode list. Primary path: mks_accordion items (the standard
     * theme markup). Fallback: bare episode links anywhere in the content.
     * Season numbers come from "SEASON N" text markers when present, or from
     * the slug itself ("-3x1" style) as a last resort.
     */
    private fun parseEpisodes(
        doc: org.jsoup.nodes.Document,
        episodeLinks: List<String>
    ): List<Episode> {
        val content = doc.selectFirst("div.entry-content") ?: doc.body()

        // season markers: <p><strong>SEASON 3</strong></p> (no links inside)
        data class Marker(val season: Int, val index: Int)
        val markers = mutableListOf<Marker>()
        val ordered = content.allElements
        content.select("p, h1, h2, h3, h4, strong").forEach { el ->
            if (el.select("a").isNotEmpty()) return@forEach
            val txt = el.text().trim()
            val m = Regex("""(?i)^(?:COMPLETE\s+)?SEASON\s*(\d{1,2})\b""").find(txt)
            if (m != null) markers.add(Marker(m.groupValues[1].toInt(), ordered.indexOf(el)))
        }

        fun seasonOf(el: org.jsoup.nodes.Element, fallbackUrl: String): Int {
            val elIdx = ordered.indexOf(el)
            var best: Int? = null
            for (mk in markers) if (mk.index in 0..elIdx) best = mk.season
            if (best != null) return best
            // slug fallback: "...-3x1" or "...-s3e1"
            Regex("""-(\d{1,2})x\d{1,3}""").find(fallbackUrl)?.let {
                return it.groupValues[1].toIntOrNull() ?: 1
            }
            Regex("""-s(\d{1,2})e\d{1,3}""", RegexOption.IGNORE_CASE).find(fallbackUrl)?.let {
                return it.groupValues[1].toIntOrNull() ?: 1
            }
            return 1
        }

        val episodes = mutableListOf<Episode>()

        // primary: accordion items
        val accordionItems = doc.select("div.mks_accordion_item")
            .filter { it.selectFirst("a[href*='archive.toonworld4all.me/episode/']") != null }
        for (item in accordionItems) {
            val heading = item.selectFirst(".mks_accordion_heading")?.text()?.trim() ?: continue
            val link = item.selectFirst("a[href*='archive.toonworld4all.me/episode/']") ?: continue
            val href = link.attr("href")
            val season = seasonOf(item, href)
            val epNum = Regex("""(?i)(?:episode|ep\.?|e)\s*(\d{1,3})""").find(heading)
                ?.groupValues?.get(1)?.toIntOrNull()
                ?: Regex("""(\d{1,2})x(\d{1,3})""").find(href)?.groupValues?.get(2)?.toIntOrNull()
                ?: episodes.size + 1
            val epName = heading.replace(
                Regex("""(?i)^episode\s*\d{1,3}\s*[:\-–]?\s*"""), ""
            ).ifBlank { null }
            episodes.add(
                newEpisode(href) {
                    this.season = season
                    this.episode = epNum
                    this.name = epName
                }
            )
        }

        // fallback: bare links (also fills anything the accordion missed)
        if (episodes.isEmpty()) {
            for (href in episodeLinks) {
                val epNum = Regex("""(\d{1,2})x(\d{1,3})""").find(href)?.groupValues?.get(2)?.toIntOrNull()
                    ?: Regex("""(?i)[\-e](\d{1,3})(?:$|/)""").find(href)?.groupValues?.get(1)?.toIntOrNull()
                    ?: episodes.size + 1
                val season = seasonOf(content, href)
                episodes.add(
                    newEpisode(href) {
                        this.season = season
                        this.episode = epNum
                    }
                )
            }
        }

        // dedupe by season+episode keeping first
        val seen = mutableSetOf<Pair<Int, Int>>()
        return episodes.filter { seen.add((it.season ?: 1) to (it.episode ?: 0)) }
    }

    // ------------------------------------------------------------------ //
    //  loadLinks
    // ------------------------------------------------------------------ //

    /** A file waiting to be resolved. */
    private class PendingFile(
        val host: String,
        val redirectPath: String,
        val quality: Int,
        val label: String,
        val cacheKey: String,
        val priority: Int,
    )

    /** Cached extractor results, keyed on the stable file identity. */
    private class CachedLink(
        val name: String,
        val url: String,
        val quality: Int,
        val referer: String,
        val headers: Map<String, String>?,
    )

    companion object {
        private const val TAG = "TW4A"

        /** episode+host+encode -> resolved host url (blank = known failure) */
        private val resolvedCache = ConcurrentHashMap<String, String>()
        /** resolved host url -> extractor output */
        private val linkCache = ConcurrentHashMap<String, List<CachedLink>>()

        /** how long a failed resolution stays cached (ms) */
        private const val FAIL_TTL = 10 * 60_000L
        private val failTimes = ConcurrentHashMap<String, Long>()

        private fun cacheFail(key: String) {
            failTimes[key] = System.currentTimeMillis()
        }
        private fun isFreshFail(key: String): Boolean {
            val t = failTimes[key] ?: return false
            return System.currentTimeMillis() - t < FAIL_TTL
        }
    }

    override suspend fun loadLinks(
        data: String,
        isCasting: Boolean,
        subtitleCallback: (SubtitleFile) -> Unit,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        if (data.isBlank() || !data.contains("archive.toonworld4all.me")) return false

        val archive = Tw4aArchive.fetchArchive(data) ?: run {
            Log.e(TAG, "failed to parse archive props for $data")
            return false
        }

        var emittedAny = false

        // watch-online streams (rare, but supported when present)
        archive.streams.forEach { stream ->
            stream.optString("play").takeIf { it.startsWith("http") }?.let { playUrl ->
                callback(
                    newExtractorLink(
                        "ToonWorld4All Watch",
                        "Watch Online",
                        playUrl,
                        ExtractorLinkType.VIDEO
                    )
                )
                emittedAny = true
            }
        }

        // ---- collect + prioritise files ---- //
        val pending = mutableListOf<PendingFile>()
        archive.encodes.forEach { encode ->
            val codec = encode.optJSONObject("readable")?.optString("codec")
                ?: encode.optString("resolution")
            val size = encode.optJSONObject("readable")?.optString("size").orEmpty()
            val quality = Regex("""(\d{3,4})""").find(encode.optString("resolution"))
                ?.groupValues?.get(1)?.toIntOrNull() ?: 0
            val label = buildString {
                append(codec)
                if (size.isNotBlank()) append(" [$size]")
            }
            val isHevc = encode.optString("codec").contains("265", true) ||
                    label.contains("hevc", true) || label.contains("x265", true)
            // playback-compatibility order: 720p x264 first, then 1080p x264,
            // 480p x264, then the HEVC encodes; hosts: hubcloud first (its dl
            // page exposes the most playable servers), then gdflix, filepress
            val encodePriority = when {
                quality == 720 && !isHevc -> 0
                quality == 1080 && !isHevc -> 1
                quality == 480 && !isHevc -> 2
                quality == 720 -> 3
                quality == 1080 -> 4
                else -> 5
            }
            encode.optJSONArray("files")?.let { files ->
                for (i in 0 until files.length()) {
                    val file = files.optJSONObject(i) ?: continue
                    val host = file.optString("host")
                    val link = file.optString("link")
                    if (link.isBlank()) continue
                    // MEGA files are AES-encrypted and cannot be played by
                    // Android players - skip them instead of broken links.
                    if (host.contains("mega", true) || link.contains("mega", true)) continue
                    val hostPriority = when {
                        host.contains("hubcloud", true) -> 0
                        host.contains("gdflix", true) -> 1
                        else -> 2
                    }
                    val cacheKey = "$data|$host|$label"
                    pending.add(
                        PendingFile(
                            host = host,
                            redirectPath = link,
                            quality = quality,
                            label = label,
                            cacheKey = cacheKey,
                            priority = encodePriority * 10 + hostPriority
                        )
                    )
                }
            }
        }
        if (pending.isEmpty()) return emittedAny
        pending.sortBy { it.priority }

        // ---- pass 1: emit everything already cached ---- //
        val toResolve = mutableListOf<PendingFile>()
        for (file in pending) {
            val resolvedUrl = resolvedCache[file.cacheKey]
            if (!resolvedUrl.isNullOrBlank() && linkCache.containsKey(resolvedUrl)) {
                emittedAny = emitHostLinks(resolvedUrl, callback) || emittedAny
                continue
            }
            if (isFreshFail(file.cacheKey)) continue
            toResolve.add(file)
        }

        // ---- pass 2: resolve new files (serial WebView, time budgeted) ---- //
        // loadLinksTimeoutMs = 300s is respected by the app (clamped to
        // 480s max in APIRepository) - stop launching new walks at 225s so
        // the last one (65s ceiling) still finishes inside the budget.
        val deadline = System.currentTimeMillis() + 225_000L
        for (file in toResolve) {
            if (System.currentTimeMillis() > deadline) break
            try {
                val ok = resolveFile(file, callback)
                emittedAny = ok || emittedAny
            } catch (e: Exception) {
                if (e is CancellationException) throw e
                Log.d(TAG, "file resolution failed (${file.host}): ${e.message}")
            }
        }
        return emittedAny
    }

    /** Re-emit previously extracted links for a resolved host url. */
    private suspend fun emitHostLinks(
        hostUrl: String,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        val cached = linkCache[hostUrl]
        if (cached != null) {
            for (l in cached) {
                callback(
                    newExtractorLink("ToonWorld4All", l.name, l.url, ExtractorLinkType.VIDEO) {
                        this.quality = if (l.quality > 0) l.quality else com.lagradost.cloudstream3.utils.Qualities.Unknown.value
                        this.referer = l.referer
                        if (l.headers != null) this.headers = l.headers
                    }
                )
            }
            return cached.isNotEmpty()
        }
        return false
    }

    private suspend fun resolveFile(
        file: PendingFile,
        callback: (ExtractorLink) -> Unit
    ): Boolean {
        // already resolved earlier? skip the shortener walk entirely
        val realUrl = resolvedCache[file.cacheKey].takeUnless { it.isNullOrBlank() }
            ?: run {
                // 1. shortener destination from the redirect chooser page
                var destination = Tw4aArchive.resolveRedirectDestination(file.redirectPath)
                if (destination.isNullOrBlank()) {
                    Log.d(TAG, "no destination for ${file.redirectPath}")
                    cacheFail(file.cacheKey)
                    return false
                }

                // 2. walk the shortener chain in the WebView until a file
                //    host appears. exe.io sessions are single-use-ish and the
                //    challenge occasionally fails on the first try - every
                //    redirect-hash fetch creates a FRESH exe.io link (verified
                //    live), so one retry with a new link is cheap insurance.
                var url = Tw4aShortener.resolve(destination)
                if (url.isNullOrBlank()) {
                    val freshDest = Tw4aArchive.resolveRedirectDestination(file.redirectPath)
                    if (freshDest != null && freshDest != destination) {
                        Log.d(TAG, "retrying ${file.host} with fresh shortener link")
                        destination = freshDest
                        url = Tw4aShortener.resolve(destination)
                    }
                }
                if (url.isNullOrBlank()) {
                    Log.d(TAG, "shortener bypass failed: $destination")
                    cacheFail(file.cacheKey)
                    return false
                }
                Log.d(TAG, "resolved ${file.host} -> $url")
                resolvedCache[file.cacheKey] = url
                url
            }

        // 3. run the matching host extractor and cache what it emits
        val collected = mutableListOf<CachedLink>()
        val capturing: (ExtractorLink) -> Unit = { link ->
            collected.add(
                CachedLink(
                    name = link.name,
                    url = link.url,
                    quality = link.quality,
                    referer = link.referer ?: "",
                    headers = link.headers,
                )
            )
            callback(link)
        }
        val hostLower = file.host.lowercase()
        when {
            hostLower.contains("hubcloud") || realUrl.contains("hubcloud") ->
                Tw4aExtractors.extractHubCloud(realUrl, file.quality, file.label, capturing)

            hostLower.contains("gdflix") || realUrl.contains("gdflix") ->
                Tw4aExtractors.extractGdflix(realUrl, file.quality, file.label, capturing)

            hostLower.contains("filepress") || realUrl.contains("filepress") ||
                    realUrl.contains("filebee") ->
                Tw4aExtractors.extractFilePress(realUrl, file.quality, file.label, capturing)

            else ->
                Tw4aExtractors.emitDirect(realUrl, file.quality, file.label, capturing)
        }
        if (collected.isNotEmpty()) linkCache[realUrl] = collected.toList()
        return collected.isNotEmpty()
    }
}
